baseURL = '/'
languageCode = 'en-us'
title = 'Frontier Arms & Supply | Gun Store in Cheyenne, WY'
theme = 'roadster'

[Params]
  copyright = "Frontier Arms & Supply"
  description = "Frontier Arms & Supply is a family-owned gun store and federally licensed firearms dealer serving Cheyenne, Wyoming since 2000. We offer new and used firearms, ammunition, optics, safes, magazines, accessories, and buy, sell, trade, and special-order firearms with knowledgeable, friendly service."
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = false
  pager = false
  customCSS = ["/css/custom.css"]

[Params.logo]
  subtitle = "New & Used Firearms, Ammunition & Accessories"
  title = "Frontier Arms & Supply"
  image = "img/fa-logo.png"

[Params.sidebar]
  home = false   # Configure layout for home page
  list = false   # Configure layout for list pages
  single = false # Configure layout for single pages
  widgets = ["social", "links"]

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  facebook = "frontierarmswy"
  #email = "info@frontierarmswy.com"

[Params.widget.links]
  title = "Quick Links"
  [[Params.widget.links.links]]
    name = "NRA"
    url = "https://home.nra.org"
    external = true
  [[Params.widget.links.links]]
    name = "Otto Road Shooting Range"
    url = "http://www.ottoroadshootingrange.com"
    external = true
  [[Params.widget.links.links]]
    name = "Well Armed Women"
    url = "https://thewellarmedwoman.com/"
    external = true
  [[Params.widget.links.links]]
    name = "Wyoming Game & Fish"
    url = "https://wgfd.wyo.gov"
    external = true
  [[Params.widget.links.links]]
    name = "ATF eForms"
    url = "https://eforms.atf.gov"
    external = true
  [[Params.widget.links.links]]
    name = "NSSF"
    url = "https://www.nssf.org"
    external = true